server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com #eureka 服务端的实例名称
  client:
    register-with-eureka: false #false 表示不想注册中心注册自己
    fetch-registry: false #false 表示自己端就是注册中心，维护实例服务，不需要检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    #默认开启，false为关闭自我保护，服务不可以则立马剔除
    enable-self-preservation: false
    #Eureka客户端向服务器发送心跳的时间间隔，默认30s，现在修改为2000ms
    eviction-interval-timer-in-ms: 20000